In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD


Using TensorFlow backend.


In [14]:
# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = np.random.randint(10, size=(1000, 1))
#y_train = keras.utils.to_categorical(y_train, num_classes=10)
x_test = np.random.random((100, 20))
y_test = np.random.randint(10, size=(100, 1))
#y_test = keras.utils.to_categorical(y_test, num_classes=10)

print ("x_train:", x_train.shape)
print ("y_train:", y_train.shape)
print ("x_test:", x_test.shape)
print ("y_test:", y_test.shape)

('x_train:', (1000, 20))
('y_train:', (1000, 1))
('x_test:', (100, 20))
('y_test:', (100, 1))


In [15]:
model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

print (len(model.layers))

5


In [16]:
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])


In [17]:
print ("start")
model.fit(x_train, y_train,
          epochs=20,
          batch_size=128)
print ("end")

start
Epoch 1/20
1000/1000 [==============================] - 0s 128us/step - loss: 2.3890 - acc: 0.1100
Epoch 2/20
1000/1000 [==============================] - 0s 30us/step - loss: 2.3601 - acc: 0.1050
Epoch 3/20
1000/1000 [==============================] - 0s 28us/step - loss: 2.3364 - acc: 0.1120
Epoch 4/20
1000/1000 [==============================] - 0s 29us/step - loss: 2.3266 - acc: 0.1040
Epoch 5/20
1000/1000 [==============================] - 0s 30us/step - loss: 2.3086 - acc: 0.1030
Epoch 6/20
1000/1000 [==============================] - 0s 30us/step - loss: 2.3039 - acc: 0.1010
Epoch 7/20
1000/1000 [==============================] - 0s 29us/step - loss: 2.3159 - acc: 0.1130
Epoch 8/20
1000/1000 [==============================] - 0s 30us/step - loss: 2.3191 - acc: 0.0940
Epoch 9/20
1000/1000 [==============================] - 0s 29us/step - loss: 2.3057 - acc: 0.1110
Epoch 10/20
1000/1000 [==============================] - 0s 29us/step - loss: 2.3001 - acc: 0.1180
Epoch 11/20


In [18]:
score = model.evaluate(x_test, y_test, batch_size=128)

100/100 [==============================] - 0s 251us/step


In [22]:
print model.metrics_names, score

['loss', 'acc'] [2.2979044914245605, 0.11999999731779099]


In [20]:
type(model)

keras.models.Sequential

In [21]:
model.metrics_names

['loss', 'acc']

In [23]:
pred = model.predict(x_test, batch_size=32, verbose=0)

In [27]:
print (type(pred), pred.shape)
print (pred[0, :])
pred_class = np.argmax(pred,axis=-1)
print (type(pred_class), pred_class.shape)

(<type 'numpy.ndarray'>, (100, 10))
[ 0.09112015  0.09656948  0.10642665  0.1043167   0.10629199  0.09725494
  0.09366933  0.10018703  0.10622171  0.09794203]
(<type 'numpy.ndarray'>, (100,))


In [44]:
print pred_class[0:10], type(pred_class), pred_class.shape
print y_test.reshape(100,)[0:10], type(y_test), y_test.reshape(100,).shape
temp = y_test.reshape(y_test.shape[0],)
print temp[0:10], type(temp), temp.shape

[2 2 2 8 2 2 4 2 2 2] <type 'numpy.ndarray'> (100,)
[4 6 2 0 7 2 3 4 7 8] <type 'numpy.ndarray'> (100,)
[4 6 2 0 7 2 3 4 7 8] <type 'numpy.ndarray'> (100,)
