In [1]:
HOMEPATH = "/home/ubuntu/fastai/"
DATAPATH = HOMEPATH + "data/Kaggle_digit_recognizer/"
print("HOMEPATH:", HOMEPATH)
print("DATAPATH:", DATAPATH)
import os

('HOMEPATH:', '/home/ubuntu/fastai/')
('DATAPATH:', '/home/ubuntu/fastai/data/Kaggle_digit_recognizer/')


In [2]:
os.chdir(HOMEPATH)
print ("os.getcwd:", os.getcwd())
import utils; reload(utils)
from utils import *

%matplotlib inline

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from __future__ import division, print_function

from keras.utils.np_utils import to_categorical

('os.getcwd:', '/home/ubuntu/fastai')


WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN 5110)
Using Theano backend.


In [40]:
def set_keras_backend(backend):

    if K.backend() != backend:
        #nb: utils has 'from keras import backend as K'
        os.environ['KERAS_BACKEND'] = backend
        reload(K)
        assert K.backend() == backend

set_keras_backend("theano")
print (K.image_dim_ordering())#th


th


In [39]:
#Each pixel column in the training set has a name like pixelx, where x is an integer between 0 and 783, inclusive.
colNames = []
colDtypes = {}
colDtypes["label"] = np.int64

for i in range(784):
    colNames.append("pixel"+str(i))
    colDtypes["pixel"+str(i)] = np.int64
print (colNames[0:2] + colNames[-2:])
colNames = ['label'] + colNames
print (colNames[0:2] + colNames[-2:])


['pixel0', 'pixel1', 'pixel782', 'pixel783']
['label', 'pixel0', 'pixel782', 'pixel783']


In [5]:
df = pd.read_csv(DATAPATH+'train.csv', names=colNames, dtype=colDtypes, header=1)

In [6]:
type(df), df.shape
#785 columns = 1 + 28*28
#reshape into numy array with shape (4199, 1, 28,28)

(pandas.core.frame.DataFrame, (41999, 785))

In [7]:
df.head(2)


label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      0       0       0       0       0       0       0       0       0   
1      1       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  

[2 rows x 785 columns]

In [8]:
uniques = list(df.label.unique())
uniques.sort()
uniques

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
pixelData = df.as_matrix()[:,1:]
print ("pixelData.shape:", pixelData.shape)
labelData = df.as_matrix()[:,0]
print ("labelData.shape:", labelData.shape, labelData[0:10])


pixelData.shape: (41999, 784)
labelData.shape: (41999,) [0 1 4 0 0 7 3 5 3 8]


In [10]:
pixelData = pixelData.reshape((41999, 28, 28))
print ("pixelData.shape:", pixelData.shape)

pixelData.shape: (41999, 28, 28)


In [11]:
X_train, X_test, y_train, y_test = train_test_split(pixelData, labelData, test_size=0.1, random_state=42)#split was 0.33

In [12]:
print ("X_train:", X_train.shape)
print ("X_test:", X_test.shape)
print ("y_train:", y_train.shape)
print ("y_test:", y_test.shape)

X_train: (37799, 28, 28)
X_test: (4200, 28, 28)
y_train: (37799,)
y_test: (4200,)


In [13]:
if len(X_test.shape)==3:
    print("expand shape")
    X_test = np.expand_dims(X_test,1)
    X_train = np.expand_dims(X_train,1)
else:
        print("expand shape already done, don't do again.")

print ("type(X_test):", type(X_test), X_test.shape)
print ("type(X_train):", type(X_train), X_train.shape)

expand shape
type(X_test): <type 'numpy.ndarray'> (4200, 1, 28, 28)
type(X_train): <type 'numpy.ndarray'> (37799, 1, 28, 28)


In [14]:
print ("X_train:", X_train.shape)
print ("X_test:", X_test.shape)


X_train: (37799, 1, 28, 28)
X_test: (4200, 1, 28, 28)


In [15]:
print ("type(y_train):", type(y_train), y_train.shape, len(y_train.shape))
print ("type(y_test):", type(y_test), y_test.shape, len(y_test.shape))

type(y_train): <type 'numpy.ndarray'> (37799,) 1
type(y_test): <type 'numpy.ndarray'> (4200,) 1


In [16]:
if len(y_test.shape)==1:
    y_train = to_categorical(y_train)
else:
    print ("y_train already onehot'd, dont try again.")

if len(y_test.shape)==1:
    y_test = to_categorical(y_test)
else:
    print ("y_train already onehot'd, dont try again.")

print ("type(y_train):", type(y_train), y_train.shape)
print ("type(y_test):", type(y_test), y_test.shape)

type(y_train): <type 'numpy.ndarray'> (37799, 10)
type(y_test): <type 'numpy.ndarray'> (4200, 10)


In [17]:
print ("y_train\n", y_train[0:5, :])
print ("y_test\n", y_test[0:5, :])

y_train
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]
y_test
 [[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [18]:
mean_px = X_train.mean().astype(np.float32)
std_px = X_train.std().astype(np.float32)

In [41]:
def showLayersInfo(model):
    print ("Number of layers : ", len(model.layers))
    count = 0
    for layer in model.layers:
        print (count, type(layer), ", trainable:", layer.trainable)
        print ("input:", layer.input_shape, ", output:",layer.output_shape, ", len(weights)", len(layer.get_weights()), "\n")
        count +=1

In [19]:
def plot_history(histories):
    #histories : list of history objects. nb: history.history dictionary structure
    print ("len(histories):", len(histories))
    if len(histories)==1: 
        history = histories
    else:
        history = {}
        for i in histories[0].history.keys():
            history[i] = []
        #create empty history to copy into
        for hist in histories:
            for key in history.keys():
                history[key] += hist.history[key]
                #print (key, len(hist.history[key]), len(history[key]))

    # list all data in history
    print(history.keys(), len(history[history.keys()[0]]))
    # summarize history for accuracy
    plt.plot(history['acc'])
    plt.plot(history['val_acc'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['train', 'validate'], loc='upper left')
    plt.show()
    # summarize history for loss
    plt.plot(history['loss'])
    plt.plot(history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'validate'], loc='upper left')
    plt.show()

In [20]:
gen = image.ImageDataGenerator()
#recall: (X_train, y_train), (X_test, y_test) = mnist.load_data()
batches = gen.flow(X_train, y_train, batch_size=64)
test_batches = gen.flow(X_test, y_test, batch_size=64)

In [21]:
def norm_input(x): return (x-mean_px)/std_px

In [22]:
def ConvBlock(layers, filters):
    #ConvBlock(layers, filters): (ZeroPadding2D+Convolution2D(filters))*layers+MaxPooling2D
    layer_list = []
    for i in range(layers):
        layer_list.append(ZeroPadding2D((1, 1)))
        layer_list.append(Convolution2D(filters, 3, 3, activation='relu'))
    layer_list.append(MaxPooling2D((2, 2), strides=(2, 2)))
    #print ("ConvBlock.layer_list:\n", layer_list)
    return layer_list


def FCBlock():
    #FCBlock: Dense, BatchNormalization, Dropout
    layer_list = []
    layer_list.append(Dense(4096, activation='relu'))
    layer_list.append(BatchNormalization())
    layer_list.append(Dropout(0.5))
    #print ("FCBlock.layer_list:\n", layer_list)
    return layer_list

In [46]:
def get_model2():
    model = Sequential()
    model.add(Lambda(norm_input, input_shape=(1, 28, 28)))
    #model.add(Lambda(norm_input, input_shape=(1, 28, 28), output_shape=(1, 28, 28)))
    #model.add(Lambda(norm_input, batch_input_shape=(1, 28, 28), output_shape=(1, 28, 28)))
    
    
    print (model.summary())
    print ("11111111111")
    #ConvBlock(layers, filters): (ZeroPadding2D+Convolution2D(filters))*layers+MaxPooling2D
    layers_to_add = []
    layers_to_add = layers_to_add + ConvBlock(2, 64)
    layers_to_add = layers_to_add + ConvBlock(2, 128)
    layers_to_add = layers_to_add + ConvBlock(3, 256)
    layers_to_add = layers_to_add + ConvBlock(3, 512)
    layers_to_add = layers_to_add + ConvBlock(3, 512)
    for layer in layers_to_add:
        print (type(layer))
        model.add(layer)
    print (model.summary())
    print (showLayersInfo(model))
    print ("22222")

    model.add(Flatten())#error here: The shape of the input to "Flatten" is not fully defined (got (512, 0, 0). 
    #Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.
    
    
    ##FCBlock: Dense, BatchNormalization, Dropout
    layers_to_add = []
    layers_to_add = layers_to_add + FCBlock()
    layers_to_add = layers_to_add + FCBlock()
    for layer in layers_to_add:
        print (type(layer))
        model.add(layer)
    print ("3333")
    print (model.summary())
    model.add(Dense(10, activation='softmax'))#nb: dense 10 output since 10 categories (10 digits 0-9)
    #
    model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    return model


In [47]:
model = get_model2()

/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:622: UserWarning: `output_shape` argument not specified for layer lambda_9 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 1, 28, 28)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))


____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
lambda_9 (Lambda)                (None, 1, 28, 28)     0           lambda_input_9[0][0]             
Total params: 0
Trainable params: 0
Non-trainable params: 0
____________________________________________________________________________________________________
None
11111111111
<class 'keras.layers.convolutional.ZeroPadding2D'>
<class 'keras.layers.convolutional.Convolution2D'>
<class 'keras.layers.convolutional.ZeroPadding2D'>
<class 'keras.layers.convolutional.Convolution2D'>
<class 'keras.layers.pooling.MaxPooling2D'>
<class 'keras.layers.convolutional.ZeroPadding2D'>
<class 'keras.layers.convolutional.Convolution2D'>
<class 'keras.layers.convolutional.ZeroPadding2D'>
<class 'keras.layers.convolutional.Convolution2D'>
<class 'keras.layers.pooling.MaxPooling2D'>
<class 'keras.layers.co

Total params: 14,713,536
Trainable params: 14,713,536
Non-trainable params: 0
____________________________________________________________________________________________________
None
Number of layers :  32
0 <class 'keras.layers.core.Lambda'> , trainable: True
input: (None, 1, 28, 28) , output: (None, 1, 28, 28) , len(weights) 0 

1 <class 'keras.layers.convolutional.ZeroPadding2D'> , trainable: True
input: (None, 1, 28, 28) , output: (None, 1, 30, 30) , len(weights) 0 

2 <class 'keras.layers.convolutional.Convolution2D'> , trainable: True
input: (None, 1, 30, 30) , output: (None, 64, 28, 28) , len(weights) 2 

3 <class 'keras.layers.convolutional.ZeroPadding2D'> , trainable: True
input: (None, 64, 28, 28) , output: (None, 64, 30, 30) , len(weights) 0 

4 <class 'keras.layers.convolutional.Convolution2D'> , trainable: True
input: (None, 64, 30, 30) , output: (None, 64, 28, 28) , len(weights) 2 

5 <class 'keras.layers.pooling.MaxPooling2D'> , trainable: True
input: (None, 64, 28, 28)

ValueError: The shape of the input to "Flatten" is not fully defined (got (512, 0, 0). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.

In [58]:
#Batchnormalisation : uses batches and test_batches created from image.ImageDataGenerator.flow(blah...)

def get_model_bn_do2():
    model = Sequential([
        
        Lambda(norm_input, input_shape=(1,28,28)),

        #ConvBlock(2, 64)
        ZeroPadding2D((1, 1)),
        Convolution2D(64, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(64, 3, 3, activation='relu'),
        MaxPooling2D((2, 2), strides=(2, 2)),

        #ConvBlock(2, 128)
        ZeroPadding2D((1, 1)),
        Convolution2D(128, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(128, 3, 3, activation='relu'),
        MaxPooling2D((2, 2), strides=(2, 2)),

        #ConvBlock(3, 256)
        ZeroPadding2D((1, 1)),
        Convolution2D(256, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(256, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(256, 3, 3, activation='relu'),
        MaxPooling2D((2, 2), strides=(2, 2)),

        #ConvBlock(3, 512)
        ZeroPadding2D((1, 1)),
        Convolution2D(512, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(512, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(512, 3, 3, activation='relu'),
        MaxPooling2D((2, 2), strides=(2, 2)),


        #ConvBlock(3, 512)
        ZeroPadding2D((1, 1)),
        Convolution2D(512, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(512, 3, 3, activation='relu'),
        ZeroPadding2D((1, 1)),
        Convolution2D(512, 3, 3, activation='relu'),
        MaxPooling2D((2, 2), strides=(2, 2)),

        Flatten(),

        #FCBlock
        Dense(4096, activation='relu'),
        BatchNormalization(),
        Dropout(0.5),

        #FCBlock
        Dense(4096, activation='relu'),
        BatchNormalization(),
        Dropout(0.5),

        Dense(10, activation='softmax')#nb: dense 10 output since 10 categories (10 digits 0-9)

        ])
    model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [59]:
get_model_bn_do2().summary()

/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:622: UserWarning: `output_shape` argument not specified for layer lambda_11 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 1, 28, 28)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))


ValueError: The shape of the input to "Flatten" is not fully defined (got (512, 0, 0). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.

In [44]:
#Batchnormalisation : uses batches and test_batches created from image.ImageDataGenerator.flow(blah...)

def get_model_bn_do():
    model = Sequential([
        Lambda(norm_input, input_shape=(1,28,28)),
        Convolution2D(32,3,3, activation='relu'),
        BatchNormalization(axis=1),
        Convolution2D(32,3,3, activation='relu'),
        MaxPooling2D(),
        BatchNormalization(axis=1),
        Convolution2D(64,3,3, activation='relu'),
        BatchNormalization(axis=1),
        Convolution2D(64,3,3, activation='relu'),
        MaxPooling2D(),
        Flatten(),
        BatchNormalization(),
        Dropout(0.5),#added dropout here since it appears overtraining & validation not converging.
        Dense(512, activation='relu'),
        BatchNormalization(),
        Dropout(0.5),
        Dense(10, activation='softmax')
        ])
    model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [45]:
get_model_bn_do().summary()

/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:622: UserWarning: `output_shape` argument not specified for layer lambda_8 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 1, 28, 28)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))


____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
lambda_8 (Lambda)                (None, 1, 28, 28)     0           lambda_input_8[0][0]             
____________________________________________________________________________________________________
convolution2d_83 (Convolution2D) (None, 32, 26, 26)    320         lambda_8[0][0]                   
____________________________________________________________________________________________________
batchnormalization_6 (BatchNorma (None, 32, 26, 26)    128         convolution2d_83[0][0]           
____________________________________________________________________________________________________
convolution2d_84 (Convolution2D) (None, 32, 24, 24)    9248        batchnormalization_6[0][0]       
___________________________________________________________________________________________

In [ ]:
def fit_model():
    model = get_model_bn_do()
    model.summary()
    print ("model.optimizer.lr:", model.optimizer.lr)
    history1 = model.fit_generator(batches, batches.n, nb_epoch=1, verbose=0,
                        validation_data=test_batches, nb_val_samples=test_batches.n)
    print("model.fit_generator(..) completed with model.optimizer.lr:", model.optimizer.lr)
    model.optimizer.lr=0.1
    history2 = model.fit_generator(batches, batches.n, nb_epoch=4, verbose=0,
                        validation_data=test_batches, nb_val_samples=test_batches.n)
    print("model.fit_generator(..) completed with model.optimizer.lr:", model.optimizer.lr)
    plot_history([history1, history2])
    model.optimizer.lr=0.01
    history3 = model.fit_generator(batches, batches.n, nb_epoch=12, verbose=0,
                        validation_data=test_batches, nb_val_samples=test_batches.n)
    print("model.fit_generator(..) completed with model.optimizer.lr:", model.optimizer.lr)
    plot_history([history1, history2, history3])
    model.optimizer.lr=0.001
    history4 = model.fit_generator(batches, batches.n, nb_epoch=18, verbose=0,
                        validation_data=test_batches, nb_val_samples=test_batches.n)
    print("model.fit_generator(..) completed with model.optimizer.lr:", model.optimizer.lr)
    plot_history([history1, history2, history3, history4])
    model.optimizer.lr=0.0001
    history5 = model.fit_generator(batches, batches.n, nb_epoch=27, verbose=0,
                        validation_data=test_batches, nb_val_samples=test_batches.n)
    print("model.fit_generator(..) completed with model.optimizer.lr:", model.optimizer.lr)
    plot_history([history1, history2, history3, history4, history5])
    return model

In [ ]:
models = [fit_model() for i in range(6)]

In [ ]:
model_path = DATAPATH + 'models/'

In [ ]:
print ("models:", type(models), len(models))

In [ ]:
for i,m in enumerate(models):
    m.save_weights(model_path+'cnn-mnist23-'+str(i)+'_2.h5')#nb: why .pkl instead of .h5? .pkl usually for pickle.

In [ ]:
evals = np.array([m.evaluate(X_test, y_test, batch_size=256) for m in models])

In [ ]:
evals_mean = evals.mean(axis=0)

In [ ]:
print ("evals_mean:", evals_mean.shape)

In [ ]:
print (evals_mean)

In [ ]:
all_preds = np.stack([m.predict(X_test, batch_size=256) for m in models])

In [ ]:
all_preds.shape

In [ ]:
avg_preds = all_preds.mean(axis=0)

In [ ]:
avg_preds.shape

In [ ]:
keras.metrics.categorical_accuracy(y_test, avg_preds).eval()

In [ ]:
#start loading test data
#Each pixel column in the training set has a name like pixelx, where x is an integer between 0 and 783, inclusive.
colNames = []
colDtypes = {}

for i in range(784):
    colNames.append("pixel"+str(i))
    colDtypes["pixel"+str(i)] = np.int64
print (colNames[0:2] + colNames[-2:])
colNames = colNames
print (colNames[0:2] + colNames[-2:])


In [ ]:
df_test = pd.read_csv(DATAPATH+'test.csv', names=colNames, dtype=colDtypes, header=0)

In [ ]:
df_test.shape

In [ ]:
test_pixelData = df_test.as_matrix()
print ("test_pixelData.shape:", test_pixelData.shape, test_pixelData.shape[0])


In [ ]:
X_test = test_pixelData.reshape((test_pixelData.shape[0], 28, 28))
print ("X_test.shape:", X_test.shape)

In [ ]:
if len(X_test.shape)==3:
    print("expand shape")
    X_test = np.expand_dims(X_test,1)
else:
        print("expand shape already done, don't do again.")

print ("type(X_test):", type(X_test), X_test.shape)


In [ ]:
all_preds = np.stack([m.predict(X_test, batch_size=256) for m in models])

In [ ]:
all_preds.shape

In [ ]:
avg_preds = all_preds.mean(axis=0)

In [ ]:
avg_preds.shape

In [ ]:
print(avg_preds[0])
print(type(avg_preds[0]))
print(type(list(avg_preds[0])))


In [ ]:
category = []
for i in range(avg_preds.shape[0]):
    category.append(np.argmax(avg_preds[i]))
    #print(i, category, avg_preds[i])
    #break
type(category), len(category), category[0:10]

In [ ]:
imageids = list(range(1, avg_preds.shape[0]+1))
print (type(imageids), len(imageids), imageids[0:5], imageids[-5:])

In [ ]:
#create dataframe, write to csv
#dataframe labels = ImageId,Label
#df = pd.read_csv(DATAPATH+'train.csv', names=colNames, dtype=colDtypes, header=1)


df = pd.DataFrame({'ImageId': imageids, 'Label': category})#, index=index, columns=['ImageId','Label'])
print (df.shape)
print (df.head())
print (df.tail())

In [ ]:
df.to_csv(DATAPATH+'submit_2.csv', index=False)

In [ ]:
os.chdir(HOMEPATH)
print ("os.getcwd:", os.getcwd())

from vgg16bn  import Vgg16BN

In [ ]:
model = Vgg16BN().model

In [ ]:
type(model)


In [ ]:
model.summary()